In [2]:
from helper_functions import *

In [5]:
get_data("^IXIC", "yfinance")

[*********************100%***********************]  1 of 1 completed

,Date,Open,High,Low,Close,Volume,Fisher50,Fisher70,Fisher90,Fisher110,...,Fisher210,Fisher230,Fisher250,Fisher270,Fisher290,Fisher310,Fisher330,Fisher350,Fisher370,Fisher390
0,2007-01-03,2429.719971,2454.620117,2394.659912,2423.159912,2435280000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2007-01-04,2423.820068,2460.510010,2413.750000,2453.429932,2104210000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2007-01-05,2445.070068,2445.070068,2420.590088,2434.250000,2060360000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2007-01-08,2435.250000,2445.629883,2421.129883,2438.199951,1905620000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2007-01-09,2443.260010,2449.870117,2423.560059,2443.830078,2144160000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3669,2021-07-30,14615.849609,14728.780273,14615.849609,14672.679688,3628750000,2.670291,2.746559,2.879880,3.002852,...,3.648552,3.693707,3.723101,3.822659,3.946037,4.079503,4.228040,4.364647,4.364647,4.364647
3670,2021-08-02,14758.599609,14770.410156,14665.669922,14681.070312,3738200000,2.586045,2.718935,2.851647,2.974320,...,3.608760,3.663582,3.683884,3.776914,3.909898,4.044502,4.182606,4.332648,4.332648,4.332648
3671,2021-08-03,14713.990234,14762.599609,14584.089844,14761.290039,4117520000,2.433890,2.634766,2.756269,2.890490,...,3.518012,3.580308,3.593753,3.682040,3.822669,3.958268,4.080826,4.248907,4.248907,4.248907
3672,2021-08-04,14747.209961,14812.370117,14734.120117,14780.530273,4319400000,2.460643,2.702534,2.814854,2.956741,...,3.577482,3.643942,3.653357,3.738644,3.883394,4.019270,4.131264,4.310834,4.310834,4.310834
3673,2021-08-05,14794.080078,14896.469727,14776.030273,14895.120117,4087320000,2.687789,2.946887,3.053623,3.198069,...,3.811782,3.880031,3.887409,3.970880,4.117181,4.252791,4.359235,4.544113,4.544113,4.544113